#!/bin/bash

# print the usage for this tool
help() {
  cat <<\HELP

  Run various alignment subtasks that make up iterations.
  WARNING: This script is meant to be used at SDF within hps/2016-align.
    Portability has not been investigated.

 USAGE:
  ./iter <cmd> [args...]

 COMMANDS:
  help           : print this help and exit
  init DETNAME   : create a new workspace for DETNAME detector
  submit DETNAME : submit tracking jobs already initialized for DETNAME detector
  watch [SLEEP]  : watch users slurm queue, reporting totals every SLEEP seconds (default 360s = 5min)
  hadd DETNAME   : merge gblplots from output of tracking using DETNAME
  pede-init DETNAME : init a pede subdirectory for DETNAME detector
  pede-run DETNAME  : run pede for DETNAME detector and apply results

HELP
}

# initialize a new detector workspace
#  1 - detector name
init() {
  local detname="${1%/}"
  if [ -d "$1" ]; then
    echo "ERROR: '${detname}' already exists."
    return 1
  fi

  if ! mkdir ${detname}; then
    echo "ERROR: Unable to create '${detname}'."
    return 1
  fi

  echo "{\"detector\": [\"${detname}\"]}" | jq . > ${detname}/tracking-vars.json

  hps-mc-job-template \
    -j 1 \
    -a ${detname}/tracking-vars.json \
    -i events tracking/physrun-2016-part-007800-HPS-PhysicsRun2016-Pass2.list 1 \
    tracking/job.json.templ \
    ${detname}/tracking-jobs.json
  return $?
}

# submit tracking jobs to slurm
#  1 - detector name
submit() {
  local detname="${1%/}"
  if [ ! -d "$detname" ]; then
    echo "ERROR: '${detname}' un-initialized."
    return 1
  fi

  
  hps-mc-batch slurm \
    --queue shared \
    --env $(which hps-mc-env.sh) \
    -S ${detname}/sh \
    -l ${detname}/log \
    -d ${detname}/scratch \
    --memory 3500 \
    -c tracking/batch.cfg \
    track_align \
    ${detname}/tracking-jobs.json \
    {1..50}
  return $?
}

# watch user's slurm queue and report summary counts to terminal
watch() {
  local squeue_poll_file="${TMPDIR:-/scratch/${USER}}/squeue-poll-$$.list"
  local sleep_time=${1:-360} 
  while true; do
    clear
    squeue -u ${USER} > ${squeue_poll_file}
    echo "$(date)"
    echo "   State  : Jobs"
    echo " Submitted: $(grep -c ${USER} ${squeue_poll_file})"
    echo " Running  : $(grep -c " R " ${squeue_poll_file})"
    echo " Pending  : $(grep -c " PD " ${squeue_poll_file})"
    sleep ${sleep_time}
  done
}

# initialize pede for input DETNAME
pede-init() {
  local detname="${1%/}"
  if [ ! -d "${detname}" ]; then
    echo "ERROR: '${detname}' uninitializaed."
    return 1
  fi

  mkdir ${detname}/pede
  find $PWD/${detname}/tracking/ -type f -name "*.bin" > ${detname}/pede/mille-bin.list || return $?
  sed "s|DETNAME|${detname}|g" pede/job.json > ${detname}/pede/job.json || return $?
  vim ${detname}/pede/job.json
  return $?
}

# run pede for input DETNAME
#  1 - DETNAME
pede-run() {
  local detname="${1%/}"
  if [ ! -d "${detname}" ]; then
    echo "ERROR: '${detname}' uninitializaed."
    return 1
  fi
  if [ ! -d "${detname}/pede" ]; then
    echo "ERROR: '${detname}' not pede initialized."
    return 1
  fi

  sbatch \
    --output=${detname}/pede/run.out \
    --job-name=pede-${detname} \
    pede/run.sh ${detname}
  return $?
}

# hadd the gbl plots for input DETNAME
#  1 - DETNAME
hadd() {
  local detname="${1%/}"
  if [ ! -d "${detname}" ]; then
    echo "ERROR: '${detname}' uninitializaed."
    return 1
  fi
  if [ ! -d "${detname}/tracking" ]; then
    echo "ERROR: '${detname}' has no tracking outputs."
    return 1
  fi
  command hadd -ff ${detname}/merged-gblplots.root ${detname}/tracking/*_gblplots.root
  return $?
}

case $1 in
  init|help|submit|watch|pede-init|pede-run|hadd)
    ${1} ${@:2}
    exit $?
    ;;
  *)
    echo "ERROR: Unrecognized command '$1'"
    exit 1
    ;;
esac
