#!/bin/bash
#  Run pyidm in the jupyter-scikit-hep container

apptainer \
  run \
  --bind /local/cms/user/eichl008/hps \
  --bind /export/scratch/users/eichl008/hps:/home/jovyan \
  --bind ${TMPDIR:-/tmp} \
  --home /export/scratch/users/eichl008/hps \
  --hostname jupyter-scikit-hep.$(uname -n) \
  /export/scratch/users/eichl008/hps/jupyter-scikit-hep.sif \
  python $@

