#!/bin/bash

set -o errexit
set -o nounset

group_by_mchi() {
  local workdir=$1
  local dir=$2
  find $dir -name "*.slcio" | sort > ${workdir}/full.list
  mchis=($(cat ${workdir}/full.list | cut -f 4 -d / | cut -f 4 -d _ | uniq))
  for mchi in ${mchis[@]}; do
    grep "mchi_${mchi}" ${workdir}/full.list > ${workdir}/mchi_${mchi}.list
  done
}

merge_group() {
  local grp=$1
  target=$(head -1 ${grp})
  target=${target//_jobid_*.slcio/.slcio}
  echo ${target}
  lcio_merge_files ${target} $(cat ${grp})
  rm $(cat ${grp})
}

if [ "$#" -eq 0 ]; then
  cat <<HELP

  merge slcio files in groups of mchi

 USAGE:
  ./merge INDIR

 ARGUMENTS:
  INDIR : input directory with files to merge
HELP
  exit 0
fi

if ! [ -d "$1" ]; then
  echo "ERROR: $1 is not a directory"
  exit 1
fi

workdir=$(mktemp -d)
group_by_mchi ${workdir} $1
for grp in ${workdir}/mchi_*.list; do
  merge_group ${grp}
done
rm -r ${workdir}
