#!/bin/bash

MAX_N_JOBS=300
SLEEP=360

main() {
  while true; do
    curr_num=$(squeue -u ${USER} | grep -c ${USER})
#    if (( curr_num < MAX_N_JOBS - 67 )); then
#      # submit next batch
#      hps-mc-batch slurm \
#        --queue shared \
#        -S /sdf/group/hps/users/eichl008/hps/2016-align/tracking/iter0/sh \
#        -l /sdf/group/hps/users/eichl008/hps/2016-align/tracking/iter0/log \
#        -d /sdf/group/hps/users/eichl008/hps/2016-align/tracking/iter0/scratch \
#        --env /sdf/group/hps/users/eichl008/hps/mc/install/bin/hps-mc-env.sh \
#        --memory 3500 -c batch.cfg \
#        track_align iter0/jobs.json \
#        {301..367}
#      break
#    else
      clear
      echo "$(date)"
      echo "   State  : Jobs"
      echo " Submitted: ${curr_num}"
      echo " Running  : $(squeue -u ${USER} | grep -c " R ")"
      echo " Pending  : $(squeue -u ${USER} | grep -c " PD ")"
#    fi
    sleep ${SLEEP}
  done
}

main
