"""!
@file pede_job.py

Run pede alignment over input bin files generated by tracking accumulation

Besides the main purpose of running the pede minimizer, we also do other helpful
tasks that are commonly done with alignment.
1. Apply the results from the pede minimizer to a new iteration of the detector
2. Construct the new iteration of the detector so that another round of tracking
    can be done
3. Merge the histogram files generated from the previous round of tracking for
    later analysis/drawing - this merging is only done if those histogram files
    exist and an output histogrma file is defined in the job JSON.
    - The histogram files are looked for by replacing the input _mille.bin suffix
      on the input files with _gblplots.bin which is the format of the outputs
      done by the tracking example.
"""
import os
from hpsmc.alignment import ApplyPedeRes, ConstructDetector

job.description = 'application of results from pede'

apply_res = ApplyPedeRes()
construct_det = ConstructDetector()

job.add([ apply_res, construct_det ])
